name: Build All

on:
  push:
    paths:
      - '**'
      - '!docker/Dockerfile'
      - '!.github/workflows/build_builder_image.yaml'

jobs:
  push_to_registry:
    name: Build project
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
      -
        name: Build all
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/tarc/buildtools2019native:latest
          options: -v ${{ github.workspace }}:/src
          run: |
            git clone src vcx
            cygwin
            cd /cygdrive/c/vcx
            ./buildall.sh 1 9 R
