name: Build Docker Image

on:
  push:
    branches:
      - 'feature/add-github-actions'

jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub packages
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: vcxb
          dockerfile: docker/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
